
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LIT_INT = 38;
  public static final int SEMI = 22;
  public static final int KLASS = 2;
  public static final int INT = 19;
  public static final int PRINTLN = 5;
  public static final int OUT = 4;
  public static final int LESS = 31;
  public static final int MINUS = 33;
  public static final int STATIC = 7;
  public static final int NOT = 36;
  public static final int AND = 30;
  public static final int LP = 27;
  public static final int COMMA = 29;
  public static final int RP = 28;
  public static final int PLUS = 32;
  public static final int MAIN = 3;
  public static final int IF = 15;
  public static final int DOT = 21;
  public static final int THIS_TOKEN = 14;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int LC = 25;
  public static final int SYSTEM = 9;
  public static final int LB = 23;
  public static final int RETURN = 12;
  public static final int EQUAL = 35;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int RC = 26;
  public static final int RB = 24;
  public static final int IDENT = 39;
  public static final int VOID = 10;
  public static final int TIMES = 34;
  public static final int ELSE = 16;
  public static final int WHILE = 17;
  public static final int PUBLIC = 6;
  public static final int EXTENDS = 11;
  public static final int LIT_BOOL = 37;
  public static final int STRING = 8;
  public static final int LENGTH = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KLASS",
  "MAIN",
  "OUT",
  "PRINTLN",
  "PUBLIC",
  "STATIC",
  "STRING",
  "SYSTEM",
  "VOID",
  "EXTENDS",
  "RETURN",
  "NEW",
  "THIS_TOKEN",
  "IF",
  "ELSE",
  "WHILE",
  "LENGTH",
  "INT",
  "BOOLEAN",
  "DOT",
  "SEMI",
  "LB",
  "RB",
  "LC",
  "RC",
  "LP",
  "RP",
  "COMMA",
  "AND",
  "LESS",
  "PLUS",
  "MINUS",
  "TIMES",
  "EQUAL",
  "NOT",
  "LIT_BOOL",
  "LIT_INT",
  "IDENT"
  };
}

